[package]
name = "gui-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = [
    "default",
    "markdown",
    "highlighter",
    "debug",
] }
reqwest = "0.12.9"
